services:

  nginx:
    image: nginx:stable
    container_name: rhapp_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started
    networks:
      - internal


  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.app
    image: rhapp:latest
    container_name: rhapp
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./cronjobs:/var/www/cronjobs
      - node_modules:/var/www/html/node_modules
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'PHP OK';"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal


  # ======================
  # 2) Cronjobs Laravel
  #=======================
  cron:
    build:
      context: .
      dockerfile: docker/cron/Dockerfile.cron
    container_name: rhapp_cron
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./cronjobs:/var/www/cronjobs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    command: >
      sh -c "printenv > /etc/environment &&
        cron -f"     


  # ========================
  # 3) Migraciones - Db Init
  #=========================
  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile.migrations
    container_name: rhapp_migrations
    working_dir: /var/www/html
    command: >
      sh -c "echo 'Esperando a DB...' && sleep 10 &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      echo 'Migrations & seed done' &&
      tail -f /dev/null"
    env_file:
      - .env.docker
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

   # ========================
  # 4) Base de Datos Mysql
  #=========================
  db:
    image: mysql:8.0
    container_name: rhapp_db
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "3308:3306"
    networks:
      - internal

    
# ============================
#  Vol√∫menes compartidos
# ============================
volumes:
  db_data:
  node_modules:



# ============================
#  Red interna
# ============================
networks:
  internal:
    driver: bridge